### ISSUE TITLE
suspicious use of opcache.enable_cli=1

### ISSUE THREAD

**Issue by rrh** [hhvm/oss-performance#19]
On ubuntu 14.04 with the default php5 installation (sudo apt-get install php5 php5-common php5-dbg)
The presence of opcache.enable_cli=1 in the conf/php.ini file is suspicious.  I suspect it isn't needed.  If I use it, then the php5 segfaults on the way out.

This stackoverflow blurb suggests to simply leave it out:
  http://stackoverflow.com/questions/25044817/zend-opcache-opcache-enable-cli-1-or-0-what-does-it-do

**Comment by rrh** [comment]
This suggestion regarding enable_cli could be of a bit of a red herring. I'm also getting core dumps when the ini file contains zend_extension=opcache.so; perhaps this is because opcache.so is statically built into system default php5, and so specifying zend_extension=opcache.so is redundant, or causes issues when cleaning up php5 on the way out.

**Comment by fredemmott** [comment]
What version of PHP5 is segfaulting? It segfaults for me on the version included in Ubuntu, but is completely fine when I build a more recent version from source.

Given it works fine in recent versions, I'd rather keep the redundancy.

The primary purpose of adding it is so that the CLI script can check that it's actually available and working.

**Comment by rrh** [comment]
The php on ubuntu 14.04 that craps out is: PHP Version => 5.5.9-1ubuntu4.5
agreed, my build of PHP 5.5 from source (and 5.6) doesn't have this problem.

**Comment by fredemmott** [comment]
So, even with everything on, https://github.com/hhvm/oss-performance/blob/master/base/php-src_config_check.php fails on 5.5.9-1ubuntu4.5

I think that build's just broken, and these options are either harmless/desirable depending on the circumstances.
