### ISSUE TITLE
use of json for batch-run.json

### ISSUE THREAD

**Issue by rrh** [hhvm/oss-performance#21]
It is an unfortunate choice to use json for human editable configuration file batch-run.json.  Json sucks for anything human maintained.

If it is possible, code the data structure in PHP, and ingest it as PHP.

Rant_on:
JSON doesn't allow for comments.  Any good scheme for configuration will get edited, comments made for posterity about what works, what doesn't work, etc.

JSON doesn't allow for terminators, only separators.  Thus every list can not end with a ',', as may happen when one edits in/edits out various lines.

NitPick: JSON has no way to encode special IEEE floating point values: NaN, +Inf, -Inf, -0.0.
Rant_off

**Comment by fredemmott** [comment]
Sorry - we generally prefer something language-agnostic, and YAML is currently either dependent on EZC or a third-party library.

Yep, the trailing commas have been bugging me too.
