### ISSUE TITLE
race conditions observed in process launch

### ISSUE THREAD

**Issue by rrh** [hhvm/oss-performance#22]
When running with --delay-process-launch=0.0, there are occasions when the launched siege finishes before the driver script checks to see if the process was launched, and the invariant
  $proc && proc_get_status($proc)['running'] === true,
fails, even though siege has come and gone successfully.

This situation happens for the siege warm ups (50 sequential hits), talking to a php5-cgi, using the helloworld example.

I also observed this for some of the other frameworks when the backing database was misconfigured, and the framework+php-cgi quit immediately.

**Comment by fredemmott** [comment]
This is unlikely to be fixed; the delay is there because of the different ways that different shells execute subprocesses.
