### ISSUE TITLE
Wordpress performance testing

### ISSUE THREAD

**Issue by shmuel-krakower** [hhvm/oss-performance#27]
Hi,
I'm not sure what's the right place to open discussions but I wanted to share a more comprehensive load testing framework for Wordpress.
I believe that if someone wants a more realistic evaluation of different installations to determine which one is best for him he may use this more complete framework: https://github.com/jmeter-templates/wordpress

Would it be appropriate to link that from the readme.md under the Wordpress section?

**Comment by fredemmott** [comment]
Thanks - we have three options:
 - evaluate other benchmark suites and decide which are worth referring to
 - including any that are mentioned to us whatever their quality
 - not linking to any

Unfortunately the first two aren't situations we want to be in, so we won't be linking to this. If you have suggestions for how to make our existing wordpress installation more generally realistic, we'd appreciate that; our advice to people who want something more realistic for their loads is to replay recorded requests against a copy of their actual installation.

**Comment by shmuel-krakower** [comment]
Fair enough.
