### ISSUE TITLE
Missing PHP5/7 extensions for Drupal suite

### ISSUE THREAD

**Issue by beberlei** [hhvm/oss-performance#55]
The drupal target requires pdo and pdo_mysql extensions, when you compile PHP with shared libraries they must be included in php.ini, so maybe `conf/php.ini` should contain:

```
;extension=pdo.so
;extension=pdo_mysql.so
```

I haven't checked other targets, but there seem to be other failures as well, only Wordpress worked for me out of the box. If you add `error_log=syslog log_errors=on` you can see the failures in syslog, but maybe it would be nice to show fatal errors or keep a log file automatically and point to the failure directly in perf.php

**Comment by fredemmott** [comment]
hhvm master no longer targets PHP5; this should be entirely removed, in favor of #84
