### ISSUE TITLE
MediaWiki outdated

### ISSUE THREAD

**Issue by demon** [hhvm/oss-performance#56]
Currently using 1.24.0. Should probably upgrade to 1.26.0, which comes out today.

**Comment by reedy** [comment]
I've done most of a patch for this, just waiting for the tarball to be released...

Just need to make an update to https://github.com/hhvm/oss-performance/blob/master/targets/mediawiki/patches/0001-LCStoreStaticArray.patch so we're not "hacking core" (ideally) and make the change in LocalSettings.php

**Comment by reedy** [comment]
The above is ready to go now!

**Comment by fredemmott** [comment]
e41b960
