### ISSUE TITLE
Uncaught exception: no factory for server type "proxygen"\n

### ISSUE THREAD

**Issue by reedy** [hhvm/oss-performance#65]
From https://github.com/hhvm/oss-performance/pull/57#issuecomment-160357333

```
Uncaught exception: no factory for server type "proxygen"\n
```

Seems there's some string quoting issue somewhere due to the \n showing like that

**Comment by reedy** [comment]
```
Exception: Unable to save cache to /tmp/hhvm-nginxuTv9ha/static.content\n
hphp failed
```

I guess this is actually a hhvm upstream bug that has presumably been fixed...

**Comment by fredemmott** [comment]
What version of HHVM are you running, and where did you get it from? You can tell the test runner to use fastcgi instead, IIRC

**Comment by fredemmott** [comment]
Dupe, #45

**Comment by reedy** [comment]
I ended up using --no-proxygen https://github.com/hhvm/oss-performance/pull/57#issuecomment-160360287

Using HipHop VM 3.6.6 (rel) on Ubuntu 12.04, from dl.hhvm.com

But yeah, #45 is an acceptable dupe
