### ISSUE TITLE
drupal 8 static content not generated

### ISSUE THREAD

**Issue by gopedib** [hhvm/oss-performance#74]
Hi, I am using this oss-framework and have been able to run and get rps numbers for wordpress, mediawiki and drupal7 with no major issues. But for this drupal 8 (no-cache and page-cache both) I am not being able to generate static contents. I tried couple of things such as changing the r/w access to files directory using "shell_exec('chmod -R a+wr sites/default/files')" from Drupal8Target.php file, as people in drupal8 forum suggested. Apparently I do not see why hhvm with this --file-cache option not being able to generate static contents for drupal8. Any suggestions/patches for that? I have been trying to make it run for 2/3 days but with no success.

hhvm perf.php --apply-patches=true --i-am-not-benchmarking --drupal8-no-cache --hhvm=/home/dibakar/hhvm_orig/hhvm/hphp/hhvm/hhvm --siege=./siege-2.78/bin/siege                        

---

*\* 2016-06-22 09:37:38 CDT
*\* Configuration: Drupal8NoCacheTarget on ~/hhvm/hphp/hhvm/hhvm

---

*\* 2016-06-22 09:37:38 CDT
*\* Installing framework
Cache rebuild complete.                                                           [ok]

---

*\* 2016-06-22 09:51:31 CDT
*\* Applying patches

---

*\* 2016-06-22 09:51:31 CDT
*\* There is no setUpTest

---

*\* 2016-06-22 09:51:31 CDT
*\* Starting Nginx
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

---

*\* 2016-06-22 09:51:32 CDT
*\* Starting PHP Engine
running hphp...
hphp failed
running hphp took 0'03" (3330343 us) wall time

Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to create static content cache' in :
Stack trace:
#0 ~/oss-performance/base/HHVMDaemon.php(216): HH\invariant_violation()
#1 ~/oss-performance/base/PerfRunner.php(83): HHVMDaemon->start()
#2 ~/oss-performance/base/PerfRunner.php(42): PerfRunner::RunWithOptionsAndEngine()
#3 ~/oss-performance/base/PerfRunner.php(17): PerfRunner::RunWithOptions()
#4 ~/oss-performance/perf.php(15): PerfRunner::RunWithArgv()
#5 ~/oss-performance/perf.php(19): perf_main()
#6 {main}

**Comment by fredemmott** [comment]
hhvm master no longer targets PHP5; this should be entirely removed, in favor of #84
