### ISSUE TITLE
How to Redirect Traffic to Interface 

### ISSUE THREAD

**Issue by inteladyne** [hhvm/oss-performance#76]
Can I push traffic through our 710? 

Then change it back to our 520-2 for traffic testing?

**Comment by mofarrell** [comment]
A little confused by your question.  It may even be misdirected.  This repo is geared towards benchmarking HHVM against PHP locally using various opensource frameworks as a load.

**Comment by inteladyne** [comment]
Understood, someone told me you could also test traffic as well but the documentation specifically said hhvm and php.  Thanks that clarifies it for me and my requester.
