### ISSUE TITLE
MediaWiki incorrectly updated to 1.28.0

### ISSUE THREAD

**Issue by reedy** [hhvm/oss-performance#86]
https://github.com/hhvm/oss-performance/commit/c7de4aa0c6d4cc1045e31df23c532cf6d036b77a#diff-9a36b08432cbdf923b28848710fcc608

The MW tar.gz was updated, mw_bench.sql.gz was not as per my comment on the commit...

Will look at doing this, and/or just updating straight to 1.29.1

**Comment by fredemmott** [comment]
hhvm master no longer targets PHP5; this should be entirely removed, in favor of #84
